language: bash

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq zsh

script:
  - SHELL=$(which bash) bash test/01_bash.t
  - SHELL=$(which zsh) zsh test/02_zsh.t
  - SHELL=$(which sh) sh test/03_sh.t
