#!/bin/sh
#
# plenvsetup http://is.gd/plenvsetup
# Mon Mar 28 12:41:07 JST 2014 v0.03 by ytnobody
#

PLENV_REPO=git://github.com/tokuhirom/plenv.git
PLENV_ROOT=$HOME/.plenv
PERLBUILDER_REPO=git://github.com/tokuhirom/Perl-Build.git
PLENV_PLUGIN_DIR=$PLENV_ROOT/plugins

if [ $(echo $SHELL | sed -n '/\/bash$/p') ]; then
    PROF_FILE=$HOME/.bash_profile
elif [ $(echo $SHELL | sed -n '/\/zsh$/p') ]; then
    PROF_FILE=$HOME/.zprofile
else
    echo 'use on bash or zsh only.'
    exit 1
fi

git --version || die "git is not installed."

die () {
    echo $1 >&2
    exit 1
}

write_profile () {
    if [ $(grep "$1" $PROF_FILE | wc -l) -le 0 ] ; then
        echo "$1" >> $PROF_FILE
    fi
}

### setup plenv
if [ ! -d $PLENV_ROOT ] ; then
    git clone $PLENV_REPO $PLENV_ROOT || die "git clone failure : $PLENV_REPO"
fi
write_profile 'export PLENV_ROOT=$HOME/.plenv'
write_profile 'export PATH=$PLENV_ROOT/bin:$PATH'
write_profile 'eval "$(plenv init -)"'

### setup Perl-Builder
mkdir $PLENV_PLUGIN_DIR
git clone $PERLBUILDER_REPO $PLENV_PLUGIN_DIR/perl-build || die "git clone failure : $PERLBUILDER_REPO"

### notify to finished installing
echo 'plenv deploy was installed.'
echo ''
echo 'To finish install plenv, please exec following command.'
echo ''
echo '    . '$PROF_FILE 
echo ''
echo 'enjoy.'
